My IIT Project/first_project/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^nettest/',include('nettest.urls',namespace='nettest')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index),

]

My IIT Project/nettest/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls.static import static
from django.conf import settings

from nettest.views import FileDetailView,FileEventView ,EventDetailView , SimulateView


urlpatterns = [
    url(r'^login/',views.login,name='login'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^registerini/',views.register,name='registerini'),
    url(r'^register/',views.register,name='register'),

    url(r'^upload/',views.upload,name='upload'),
    url(r'^graphs/',views.graphs,name='graphs'),
    url(r'^simparam/',views.simparam,name='simparam'),
    url(r'^comparegraph/',views.comparegraph,name='comparegraph'),
    url(r'^livegraphs/',views.livegraphs,name="livegraphs"),
    url(r'^searchini/',views.searchini,name='searchini'),
    url(r'^searchwithid/',views.searchwithid,name='searchwithid'),
    url(r'^captureini/',views.captureini,name='captureini'),
    url(r'^simulate/',SimulateView.as_view(),name='simulate'),
    url(r'^admin/',views.admin,name='admin'),
    url(r'^execute/',views.execute,name='execute'),
    url(r'^searcheve/',views.searchevent,name='search'),
    url(r'^captureini/',views.captureini,name='captureini'),
    url(r'^capture/',views.capture,name='capture'),

    url(r'^manage/',views.manage,name='manage'),
    url(r'^deleterow/',views.deleterow,name='deleterow'),
    url(r'^updaterow/',views.updaterow,name='updaterow'),
    url(r'^deleteall/',views.deleteall,name='deleteall'),

    url(r'^nara/',views.nara),
    url(r'^narayan/',views.narayan),

    url(r'^generalsettings/',views.generalsettings),
    url(r'^configure/',views.configure),
    url(r'^configureinterfaces/',views.configureinterfaces),


    url(r'^deletesettings/',views.deletesettings), 
    url(r'^selecttoaddscanned/',views.selecttoaddscanned),
    url(r'^scanclienttodatabase',views.scanclienttodatabase),
    url(r'^selecttomonitor/',views.selecttomonitor),
    url(r'^addclienttoselecttomonitor/',views.addclienttoselecttomonitor),
    url(r'^showmonitorform/',views.showmonitorform),   

    url(r'^selecttosimulate/',views.selecttosimulate),
    url(r'^addclienttoselecttosimulate/',views.addclienttoselecttosimulate),
    url(r'^showsimulationform/',views.showsimulationform),
    url(r'^store/',views.store,name='store'),
 
    url(r'^executetsharkmonitor',views.executetsharkmonitor),
    url(r'^executetshark/',views.executetshark),
    url(r'^$',views.index),
]+  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

My IIT Project/templates/execute.html
{% extends "base.html" %}
{% block graph %}<li class="active">{% endblock %}
{% block previous %}<li>{% endblock %}
{% block simulate %}<li>{% endblock %}
{% block setttings %}<li>{% endblock %}
<!--
<table border="1">
<tr>
    <th>ID</th>
    
   
    <th>date</th>
    <th>SOURCE IP</th>
    <th>DESTINATION IP</th> 
    <th>SUM OF UPLOADED PACKETS</th>
    <th>SUM OF DOWNLOADED PACKETS</th>
    <th>UPLOAD MEAN</th> 
    <th>DOWNLOAD MEAN</th>
    <th>UPLOAD BANDWIDTH</th>
    <th>DOWNLOAD BANDWIDTH</th>
   
</tr>
{% for row in data2 %}
<tr>

<td>{{row.0}}</td>
<td>{{row.1}}</td>
<td>{{row.2}}</td>

<td>{{row.3}}</td>
<td>{{row.4}}</td>
<td>{{row.5}}</td>
<td>{{row.6}}</td>
<td>{{row.7}}</td>
<td>{{row.8}}</td>
<td>{{row.9}}</td>


</tr>
{% endfor %}
</table>

-->
{% block content %}
<br><br>   
<p>UPLOADED PACKETS </p>



 {% load static %}
<img src="{% static 'nettest/mainplotg.jpeg' %}">image</img>
<p>downloaded packets</p>


 {% load static %}
<img src="{% static 'nettest/plotdown.jpeg' %}">image</img> 
 
 
<p>piechart for uploaded packets</p>

{% load static %}

<img src="{% static 'nettest/piechart2.jpeg' %}">image</img>



 {% load static %}
<p>piechart for downloaded packets</p>
<img src="{% static "nettest/piechart2down.jpeg" %}">image</img> 

<p>LINE GRAPH </p>



 {% load static %}
<img src="{% static 'nettest/linegraph.jpeg' %}">image</img>
<p>downloaded packets</p>

<p>line graph for downloaded packets bandwidth</p>

{% load static %}

<img src="{% static 'nettest/linegraph2.jpeg' %}">image</img>











</br>
<!--<a href="{% url 'nettest:admin' %}"><b>RETURN TO HOME<b></a></br> -->

{% endblock %}

My IIT Project/templates/fail.html
<!DOCTYPE html>
<html>
<body>
<p>Login Failed.Wrong Details</p>
</br>

<p>Click <a href="{% url 'nettest:registerini' %}">here</a>to login again</p>

My IIT Project/templates/generalsettings.html
{% extends "base.html" %}
{% block main %}<div id="main-slider">{% endblock %}
{% block graph %}<li>{% endblock %}
{% block previous %}<li>{% endblock %}
{% block simulate %}<li>{% endblock %}
{% block settings %}<li class="active">{% endblock %}

{% block content %}
<script>
function Clicked()
{
if(confirm("Do you want to delete all rules"))
return true;
else
return false;

}
</script>
<div class="container">
<br><br><br><br><br><br>
<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-1">
 <img src="/static/images/inst.jpg" height="110" width="100" class="img-rounded">
<a href="/nettest/guide" style="color:#000000">Installation Guide</a>
</div>
<div class="col-sm-1"></div>
<div class="col-sm-1">
 <img src="/static/images/conf.png" height="110" width="100" class="img-rounded">
<a href="/nettest/configure/" style="color:#000000">Configure Interfaces</a>
</div>
<div class="col-sm-1"></div>
<div class="col-sm-1">
 <img src="/static/images/images/del.jpg" height="110" width="100" class="img-rounded">
<a href="/nettest/deletesettings/" style="color:#000000" onclick="return Clicked();">Delete All rules</a>
</div>
<div class="col-sm-1"></div>
<div class="col-sm-1">
 <img src="/static/images/mana.jpg" height="110" width="100" class="img-rounded">
<a href="/nettest/manage/" style="color:#000000">Manage Systems</a>
</div>

<div class="col-sm-2"></div>
</div>
{% endblock %}

My IIT Project/templates/graphs.html
{% extends "base.html" %}
{% block simulate %}<li>{% endblock %}
{% block main %}<div id="main-slider">{% endblock %}
{% block graph %}<li class="active">{% endblock %}
{% block previous %}<li>{% endblock %}

<br>   
<p>Uploaded packets percentage(Piechart)</p>
{{num}}

{%block content%}
{%for  image in images %}
<img src='/static/nettest/{{image}}' />
{% endfor%}


{% endblock %}

My IIT Project/templates/home.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
{%load staticfiles%}
    <head>
        <title>MAIN PAGE</title>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
            <link rel="stylesheet" href="{% static 'css/home.css' %}">
            <link rel="stylesheet" href="{% static 'css//bootstrap.min.css' %}">
            
            

    </head>

    <body>
<!--
<div class="container" align="right">

  <div class="btn-group" align="right">
   
    <input type="button" class="btn btn-info" onClick="window.location.href='{% url 'nettest:homeset' %}'" value="settings"/></a>
    <input type="button" class="btn btn-info" onClick="window.location.href='{% url 'nettest:homeprodet' %}'" value="User details"/></a>
    <input type="button" class="btn btn-info" onClick="window.location.href='{% url 'nettest:homemcsel' %}'" value="Other active users"/></a>
   
    <input type="button" class="btn btn-info" onClick="window.location.href='{% url 'nettest:login' %}'" value="logout"/></a>

  </div>
</div>

    -->      


<div class="container-fluid">
    <h1>hi! {{username}} ,you are now logged in!</h1>

  <div class="row">
    <div  class="col-sm-6" style="background-color:lavender;height:250px;">
    
   
  <form enctype="multipart/form-data" method="POST" action="{% url 'display:homeupload' %}">
        
   
            {% csrf_token %}
           
            
            

         <input type="submit" class="btn btn-info btn-lg center-block"  name="submit" value="Graphs" style={"align:center"} />
        </form>
    

</div>
    

<div class="col-sm-6" style="background-color:HoneyDew;height:250px;">

    
  
        <form enctype="multipart/form-data" method="POST" action="{% url 'display:homesearchini' %}">
        

            {% csrf_token %}
            
            

            <input type="submit" class="btn btn-info btn-lg center-block"  value="Retrieve events"  />
        </form>
      
</div>
    
</div>
    


</div>
    
  </div>
</div>

</body>
</html>

My IIT Project/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>Landy - Parallax App Landing Page</title>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- CSS 
        ================================================== -->
    <!-- Bootstrap 3-->
    <link href="static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic|Roboto+Condensed:300italic,400italic,700italic,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700' rel='stylesheet' type='text/css'>
    <!-- Template Styles -->
    <link href="static/css/style.css" rel="stylesheet" media="screen">
      </head>
  <body>
	  
	  <!-- NAVBAR
	      ================================================== -->
	  <nav class="navbar navbar-default" role="navigation">
	  	  <div class="container">
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    
			    <!--Replace text with your app name or logo image-->
			    <a class="navbar-brand" href="#">Landy</a>
			    
			  </div>
			  <div class="collapse navbar-collapse navbar-ex1-collapse">
			    <ul class="nav navbar-nav">
			      <li><a onclick="$('header').animatescroll({padding:71});">Start</a></li>
			      <li><a onclick="$('.detail').animatescroll({padding:71});">Screens</a></li>
			      <li><a onclick="$('.features').animatescroll({padding:71});">Features</a></li>
			      <li><a onclick="$('.social').animatescroll({padding:71});">Social	</a></li>
			    </ul>
			  </div>
		  </div>
	  </nav>
	  
	  
	   <!-- HEADER
	   ================================================== -->	  
	  <header>
		 <div class="container">
			 <div class="row">
				 <div class="col-md-12">
					  <h1>Hello World!</h1>
					  <p class="lead">TEST TOUR NETWORK HERE</p>
					  
					  <div class="carousel-iphone">
					  	<div id="carousel-example-generic" class="carousel slide">
					    
					    <!-- Indicators -->
					    <ol class="carousel-indicators">
					      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
					      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
					    </ol>
					  
					    <!-- Wrapper for slides -->
					    <div class="carousel-inner">
					      <div class="item active">
					        <img src="static/img/screenshots/app-1.png" alt="App Screen 1">
					      </div>
					      <div class="item">
					        <img src="static/img/screenshots/app-2.png" alt="App Screen 2">
					      </div>
					      <div class="item">
					        <img src="static/img/screenshots/app-3.png" alt="App Screen 3">
					      </div>
					      
					    </div>
					  </div>
					</div>
				</div>	  
			</div>    
		</div>
	 </header>
	  
	  
	  <!-- PURCHASE
	  <section class="purchase">
		  <div class="container">
			  <div class="row">
				  <div class="col-md-offset-2 col-md-8">
					 <h1>TEST YOUR NETWORK</h1>					 	  
				  </div>
			  </div>
		  </div>
	  </section>
	  
	  

	 <!-- 
	 FEATURES
	  <section class="features">
		  <div class="container">
			  <div class="row">
				
				  <div class="col-md-4">
					  <div class="circle"><i class="icon-bookmark"></i></div>
					  <h2>Quick &amp; Easy Setup</h2>
					  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
				  </div>
				
				  <div class="col-md-4">
					  <div class="circle"><i class="icon-keypad"></i></div>
					  <h2>Parallax Scrolling</h2>
					  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
				  </div>
				 
				  <div class="col-md-4">
					  <div class="circle"><i class="icon-like"></i></div>
					  <h2>Responsive Design</h2>
					  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
				  </div>
				  
			  </div>
		  </div>
	  </section>
	  
	
	 <!-- SOCIAL
	  <section class="social">
	  	<div class="container">
	  		  <div class="row">
	  			  <div class="col-md-12">
	  			  	<h2>Connect with us</h2>
	  			   	<a class="icon-facebook"></a>
	  			   	<a class="icon-twitter"></a>
	  			   	<a class="icon-google"></a>
	  			   	<a class="icon-instagram"></a>
	  			   	<a class="icon-pinterest"></a>
	  			   </div>
	  		  </div>
	  	  </div>	  
	  </section>
	  
	
	  GET IT 
	     ================================================== 
	  <section class="get-it">
	  	<div class="container">
	  		<div class="row">
	  			<div class="col-md-12">
	  				<h1>Avaialable now on the App Store</h1>
	  				<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
	  				<button type="button" class="app-store"></button>
	  			</div>
	  			<div class="col-md-12">
	  				<hr />
		  			<ul>
	                	<li><a href="#link-here">Contact</a></li>
	                	<li><a href="#link-here">Twitter</a></li>
	                	<li><a href="#link-here">Press</a></li>
	                	<li><a href="#link-here">Support</a></li>
	                	<li><a href="#link-here">Developers</a></li>
	                	<li><a href="#link-here">Privacy</a></li>
                	</ul>
	  			</div>
	  		</div>
	  	</div>
	  </section>
	  -->
	 
	 <!-- JAVASCRIPT
	     ================================================== -->
    <script src="static/js/jquery.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/animatescroll.js"></script>
    <script src="static/js/scripts.js"></script>
    <script src="static/js/retina-1.1.0.min.js"></script>
  	
</html>

My IIT Project/templates/livegraphs.html
<html>
<head>

<title>Highcharts</title>
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
   <script src="http://code.highcharts.com/highcharts.js"></script>  
   <script src="http://code.highcharts.com/highcharts-3d.js"></script>  
<!--<div id="chart_container1" style="width:100%; height:400px;"></div>

<div id="chart_container2" style="width:100%; height:400px;"></div>
<div id="chart_container" style="width:100%; height:400px;"></div>-->
</head>
<body>
<div id="container6" style="width: 550px; height: 400px; margin: 0 auto"></div>
<div id="chart_container3" style="width:100%; height:400px;"></div>
<div id="chart_container1" style="width:100%; height:400px;"></div>

<div id="chart_container2" style="width:100%; height:400px;"></div>
<script language="JavaScript">

$(function () {
$('#chart_container1').highcharts({
chart: {
type: 'bar'
},
title: {
text: 'percentage of packets {{pcid}}'
},
xAxis: {
categories: ['1-250','251-500','501-750','751-1000','1001-1250','1251-1500','1500-1750','>1750']
},
yAxis: {
title: {
text: 'percentage'
}
},
series: [{
name: 'upload',
data: {{uplist}}
}, {
name: 'download',
data:{{downlist}}
}]

});
});


$(document).ready(function() {  
   var chart = {      
      type: 'pie',     
      options3d: {
         enabled: true,
         alpha: 45,
         beta: 0
      }
   };
   var title = {
      text: 'Piechart of uploaded packets % for {{pcid}}'   
   };   
   var tooltip = {
      pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
   };

   var plotOptions = {
      pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          depth: 35,
          dataLabels: {
             enabled: true,
             format: '{point.name}'
          }
      }
   };   
   var series= [{
         type: 'pie',
            name: ['uploaded packets'],
            data: [['1-250',{{uplist.0}}],['251-500',{{uplist.1}}],['501-750',{{uplist.2}}],['751-1000',{{uplist.3}}],['1001-1250',{{uplist.4}}],['1251-1500',{{uplist.5}}],['1501-1750',{{uplist.6}}],['>1751',{{uplist.7}}] ]
                
            
   }];     
      
   var json = {};   
   json.chart = chart; 
   json.title = title;       
   json.tooltip = tooltip; 
   json.plotOptions = plotOptions; 
   json.series = series;   
   $('#container6').highcharts(json);
});

$(document).ready(function() {
   var chart = {
      type: 'pie',
      options3d: {
         enabled: true,
         alpha: 45,
         beta: 0
      }
   };
   var title = {
      text: 'Piechart of downloaded packets for % {{pcid}} '
   };
   var tooltip = {
      pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
   };

   var plotOptions = {
      pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          depth: 35,
          dataLabels: {
             enabled: true,
             format: '{point.name}'
          }
      }
   };
   var series= [{
         type: 'pie',
            name: ['downloaded'],
            data: [['1-250',{{downlist.0}}],['251-500',{{downlist.1}}],['501-750',{{downlist.2}}],['751-1000',{{downlist.3}}],['1001-1250',{{downlist.4}}],['1251-1500',{{downlist.5}}],['1501-1750',{{downlist.6}}],['>1751',{{downlist.7}}] ]
 }];

   var json = {};
   json.chart = chart;
   json.title = title;
   json.tooltip = tooltip;
   json.plotOptions = plotOptions;
   json.series = series;
   $('#chart_container3').highcharts(json);
});

</script>
</body>
</html>

My IIT Project/templates/managesys.html
{% extends "base.html" %}
{% block main %}<div id="main-slider">{% endblock %}
{% block graph %}<li>{% endblock %}
{% block previous %}<li>{% endblock %}
{% block simulate %}<li>{% endblock %}
{% block settings %}<li class="active">{% endblock %}
{% block content %}
<div class="container">

       
        <h3>List of PC's</h3>
        
        <table class="table table-striped" style="color:#000000">
        <th>PC IP</th>
        <th>PC name</th>
        <th>Delete</th>
        <th>Update</th>
        {% for host in hosts %}
        <tr>
        



        <td>{{ host.hostip }}</td><td>{{ host.hostname }} </td>
		<form id="delform" method="POST" action="{% url 'nettest:deleterow' %}">
		 {% csrf_token %}
		<td><button type="submit" class="btn btn-primary" name="delete" value="{{host.id}}" >Delete</button></td>
		</form>
		<form method="POST" class="form-horizontol" action="{% url 'nettest:updaterow' %}">
		{% csrf_token %}
		<td><input type="button" data-id="{{host.id}}"value="update" id="submitBtn" data-toggle="modal" data-target="#confirm-submit" class="open-AddBookDialog btn btn-primary"/></td>
		<script>
    $(document).on("click", ".open-AddBookDialog", function () {
     var myBookId = $(this).data('id');
     $(".modal-body #btn").val( myBookId );

	 });

     </script>
        <div class="modal fade" id="confirm-submit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Update details
            </div>
            <div class="modal-body">
			
           
			
            <div class="control-group">
        <label class="control-label" for="pcip">Ip Address:</label>
        <div class="controls">
        <input type="text" id="pcip" name="pcip" placeholder="Ip Address" class="form-control"/>
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="pcname">PC Name:</label>
        <div class="controls">
            <input type="text" name="pcname" id="pcname" placeholder="IP name" class="form-control" value=""/><br>
        </div>
        </div>
         	    
         <button type="submit" name="update" id="btn" class="btn btn-success success" value="">update</button>       
			
  <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            
        </div>
		
    </div>
</div>
</div>
</div>
       
</form>
 </tr>

        {% endfor %}
        </table>
		<form method="POST" action="{% url 'nettest:deleteall' %}">
		{% csrf_token %}
		<center><button type="submit" class="btn btn-primary">Delete All</button></center>
		</form>
     
</div>
		{% endblock %}

My IIT Project/templates/naradtest.html
<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>Document</title>
 </head>
 <body>
  


<form method="post" action="/nettest/narayan/">

        {% csrf_token %}
        <h3>List of PC's</h3>
        <div id="try1"></div>
        <table class="table table-striped" style="width:600px;color:#000000">
        <th>SELECT</th>
        <th>PC IP</th>
        <th>PC NAME</th>
    
        {% for host in hosts %}
        <tr>
        


            <td style="height:20px"><input type="checkbox" name="hostid" id="sim" value="{{ host.id }}"></td>
        <td>{{ host.hostip }}</td><td>{{ host.hostname }} </td>

        </tr>

        {% endfor %}
        </table>
	



<input type="submit" name="simulate"  value="S1">
<input type="submit" name="monitor" value="S2">

</form>








 </body>
</html>

My IIT Project/templates/noerror.html
    <!DOCTYPE html>
    <html>

<head>
<head>
        <title>CAPTURE</title>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
             {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'css/home.css' %}">
            <link rel="stylesheet" href="{% static 'css//bootstrap.min.css' %}">
            
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
             

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
<script src="first.js"></script>
            
            

    </head>
     <body>

<div class="container" align="right">

  <div class="btn-group" align="right">
   
    <input type="button" class="btn btn-primary" onClick="window.location.href='{% url 'nettest:admin' %}'" value="back to home"/></a>
    
    <input type="button" class="btn btn-primary" onClick="window.location.href='{% url 'nettest:login' %}'" value="logout"/></a>
  </div>
</div>
</head>

        <body>
</br>
</br>
</br>

            <p>confirm</p>
values after test is conducted:  



<table border="1">
<tr>
    <th>ID</th>
    
 
    <th>SOURCE IP</th>
    <th>Duration</th> 
<th>Total Packet<th>
<!--	<th>total no. of uploaded packets</th>
	<th>total no. of downloaded packets</th>-->
    <th>SUM OF size of uploadedPACKETS</th>
    <th>SUM OF size of downloaded PACKETS</th>
    <th>UPLOAD MEAN</th> 
    <th>DOWNLOAD MEAN</th>
	<th>Avg Packet upload per sec</th>
	<th>Avg Pacet download per sec</th>

    <th>UPLOAD BANDWIDTH</th>
    <th>DOWNLOAD BANDWIDTH</th>
   
</tr>
{% for obj in tobj %}
<tr>

<td>{{obj.mip}}</td>
<td>{{obj.mtime}}</td>
<td>{{obj.mtotal_pkt}}</td>
<td>{{obj.sumup}}</td>
<td>{{obj.sumdown}}</td>
<td>{{obj.meanup}}</td>
<td>{{obj.meandown}}</td>
<td>{{obj.avg_u_s}}</td>
<td>{{obj.avg_d_s}}</td>
<td>{{obj.avg_u_s}}</td>
<td>{{obj.avg_d_s}}</td>
<td>{{obj.bandup}}</td>
<td>{{obj.banddown}}</td>

{% endfor %}


</tr>
</table>




 
</br>

</br>

             
        <body>
    </html>